/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f7f9fb',
        'on-surface-variant': '#45464d',
        'on-tertiary': '#ffffff',
        'on-background': '#191c1e',
        'tertiary-fixed': '#fcdeb5',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f2f4f6',
        secondary: '#0058be',
        primary: '#000000',
        'outline-variant': '#c6c6cd',
        'surface-container': '#eceef0',
        outline: '#76777d',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-surface': '#191c1e',
        'inverse-primary': '#bec6e0',
        'secondary-fixed': '#d8e2ff',
        'surface-variant': '#e0e3e5',
        tertiary: '#000000',
        'on-secondary-fixed-variant': '#004395',
        'inverse-surface': '#2d3133',
        'on-primary-container': '#7c839b',
        'on-secondary-container': '#fefcff',
        'surface-container-high': '#e6e8ea',
        'on-secondary-fixed': '#001a42',
        'secondary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#271901',
        'surface-dim': '#d8dadc',
        'primary-fixed': '#dae2fd',
        'surface-tint': '#565e74',
        'surface-container-highest': '#e0e3e5',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed-variant': '#574425',
        surface: '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'tertiary-fixed-dim': '#dec29a',
        'tertiary-container': '#271901',
        'on-primary-fixed-variant': '#3f465c',
        'primary-container': '#131b2e',
        'on-error-container': '#93000a',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-container': '#98805d',
        'primary-fixed-dim': '#bec6e0',
        'secondary-container': '#2170e4',
        'on-primary-fixed': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '24px',
        'container-max': '1440px',
        xs: '8px',
        lg: '32px',
        xl: '48px',
        base: '4px',
        gutter: '24px',
        sm: '16px',
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'headline-md-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'body-md': ['Inter'],
        'mono-label': ['JetBrains Mono'],
        'label-caps': ['Inter'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md-mobile': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'mono-label': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
